-- ==============================================================================
-- VoiceKhata Supabase Database Schema & RLS Setup
-- Run this SQL in your Supabase Project: SQL Editor -> New Query -> Run
-- ==============================================================================

-- 1. Enable Required Extensions
create extension if not exists "uuid-ossp";
create extension if not exists "pgcrypto";

-- 2. User Profiles Table
create table if not exists public.user_profiles (
  firebase_uid         text primary key,
  full_name            text,
  country              text default 'India',
  currency             text default 'INR',
  monthly_income       numeric,
  income_source        text default 'Salary',
  savings_goal         numeric,
  financial_experience text default 'Beginner',
  dob                  text,
  profile_pic          text,
  created_at           timestamptz default now()
);

-- 3. Transactions Table
create table if not exists public.transactions (
  id           bigint generated by default as identity primary key,
  firebase_uid text not null references public.user_profiles(firebase_uid) on delete cascade,
  transaction  text not null,
  category     text not null,
  amount       numeric not null,
  date         text not null,
  type         text not null,
  method       text default 'UPI',
  status       text default 'Completed',
  created_at   timestamptz default now()
);

-- 4. Budgets Table
create table if not exists public.budgets (
  id           text default gen_random_uuid()::text primary key,
  firebase_uid text not null references public.user_profiles(firebase_uid) on delete cascade,
  category     text not null,
  amount       numeric not null,
  spent        numeric default 0,
  month        text not null,
  duration     text default 'Monthly',
  created_at   timestamptz default now()
);

-- 5. Savings Goals Table
create table if not exists public.savings_goals (
  id            text default gen_random_uuid()::text primary key,
  firebase_uid  text not null references public.user_profiles(firebase_uid) on delete cascade,
  name          text not null,
  target_amount numeric not null,
  saved_amount  numeric default 0,
  deadline      text,
  color         text default '#6366F1',
  created_at    timestamptz default now()
);

-- 6. SIP Plans Table
create table if not exists public.sip_plans (
  id              text default gen_random_uuid()::text primary key,
  firebase_uid    text not null references public.user_profiles(firebase_uid) on delete cascade,
  monthly_amount  numeric not null,
  duration_years  numeric not null,
  expected_return numeric not null,
  start_date      text not null,
  active          boolean default true,
  created_at      timestamptz default now()
);

-- 7. Manual Investments Table
create table if not exists public.manual_investments (
  id              text default gen_random_uuid()::text primary key,
  firebase_uid    text not null references public.user_profiles(firebase_uid) on delete cascade,
  name            text not null,
  type            text not null,
  amount_invested numeric not null,
  expected_return numeric default 0,
  added_at        text not null
);

-- 8. Recurring Transactions Table
create table if not exists public.recurring_transactions (
  id           text default gen_random_uuid()::text primary key,
  firebase_uid text not null references public.user_profiles(firebase_uid) on delete cascade,
  transaction  text not null,
  category     text not null,
  amount       numeric not null,
  type         text default 'expense',
  method       text default 'UPI',
  frequency    text default 'monthly',
  start_date   text not null,
  next_run     text not null,
  end_date     text,
  active       boolean default true,
  created_at   timestamptz default now()
);

-- 9. Recurring Savings Table
create table if not exists public.recurring_savings (
  id           text default gen_random_uuid()::text primary key,
  firebase_uid text not null references public.user_profiles(firebase_uid) on delete cascade,
  label        text not null,
  amount       numeric not null,
  frequency    text default 'monthly',
  active       boolean default true,
  created_at   timestamptz default now()
);

-- 10. Notifications Table
create table if not exists public.notifications (
  id           text default gen_random_uuid()::text primary key,
  firebase_uid text not null references public.user_profiles(firebase_uid) on delete cascade,
  type         text not null,
  title        text not null,
  message      text not null,
  metadata     jsonb default '{}'::jsonb,
  read         boolean default false,
  created_at   timestamptz default now()
);

-- 11. Alert Rules Table
create table if not exists public.alert_rules (
  id           text default gen_random_uuid()::text primary key,
  firebase_uid text not null references public.user_profiles(firebase_uid) on delete cascade,
  name         text not null,
  condition    text not null,
  threshold    numeric,
  category     text,
  channel      text[] default array['in_app']::text[],
  enabled      boolean default true,
  created_at   timestamptz default now()
);

-- 12. Merchant Memory Table
create table if not exists public.merchant_memory (
  id              text default gen_random_uuid()::text primary key,
  firebase_uid    text not null,
  raw_input       text not null,
  normalized_name text not null,
  merchant_type   text default 'other',
  category        text not null,
  tags            text[] default array[]::text[],
  confidence      numeric default 0.5,
  hit_count       integer default 1,
  created_at      timestamptz default now(),
  updated_at      timestamptz default now()
);

-- 13. Yearly Budget Summary Table
create table if not exists public.yearly_budget_summary (
  id           text default gen_random_uuid()::text primary key,
  firebase_uid text not null references public.user_profiles(firebase_uid) on delete cascade,
  year         integer not null,
  month        integer not null,
  category     text not null,
  budgeted     numeric default 0,
  spent        numeric default 0,
  created_at   timestamptz default now()
);

-- 14. Gmail Sync & Backend Tables
create table if not exists public.gmail_tokens (
  firebase_uid  text primary key references public.user_profiles(firebase_uid) on delete cascade,
  access_token  text,
  refresh_token text,
  expiry_date   bigint,
  created_at    timestamptz default now(),
  updated_at    timestamptz default now()
);

create table if not exists public.processed_emails (
  id           text default gen_random_uuid()::text primary key,
  firebase_uid text not null references public.user_profiles(firebase_uid) on delete cascade,
  gmail_id     text not null,
  processed_at timestamptz default now()
);

-- 15. Chat Sessions Table
create table if not exists public.chat_sessions (
  id           text default gen_random_uuid()::text primary key,
  firebase_uid text not null references public.user_profiles(firebase_uid) on delete cascade,
  title        text,
  message_count integer default 0,
  created_at   timestamptz default now(),
  updated_at   timestamptz default now(),
  last_message_at timestamptz default now()
);

-- 16. Chat Messages Table
create table if not exists public.chat_messages (
  id           text default gen_random_uuid()::text primary key,
  chat_id      text not null references public.chat_sessions(id) on delete cascade,
  role         text not null check (role in ('user', 'assistant', 'system')),
  content      text not null,
  created_at   timestamptz default now()
);

-- 17. Create Performance Indexes
create index if not exists idx_transactions_uid_date on public.transactions(firebase_uid, date);
create index if not exists idx_budgets_uid_month on public.budgets(firebase_uid, month);
create index if not exists idx_savings_goals_uid on public.savings_goals(firebase_uid);
create index if not exists idx_notifications_uid on public.notifications(firebase_uid, created_at desc);
create index if not exists idx_recurring_uid on public.recurring_transactions(firebase_uid);
create index if not exists idx_merchant_memory_uid on public.merchant_memory(firebase_uid);
create index if not exists idx_chat_sessions_uid on public.chat_sessions(firebase_uid, updated_at desc);
create index if not exists idx_chat_messages_chat_id on public.chat_messages(chat_id, created_at asc);

-- 18. RPC Stored Functions
create or replace function public.set_uid(uid text)
returns void
language plpgsql
security definer
as $$
begin
  perform set_config('app.current_user_id', uid, false);
end;
$$;

create or replace function public.upsert_user_profile(p_uid text, p_full_name text)
returns public.user_profiles
language plpgsql
security definer
as $$
declare
  v_profile public.user_profiles;
begin
  insert into public.user_profiles (firebase_uid, full_name)
  values (p_uid, coalesce(p_full_name, 'User'))
  on conflict (firebase_uid)
  do update set
    full_name = coalesce(public.user_profiles.full_name, excluded.full_name)
  returning * into v_profile;

  return v_profile;
end;
$$;

create or replace function public.get_gmail_tokens_encrypted(p_uid text)
returns setof public.gmail_tokens
language sql
security definer
as $$
  select * from public.gmail_tokens where firebase_uid = p_uid;
$$;

create or replace function public.upsert_gmail_tokens_encrypted(
  p_uid text,
  p_access_token text,
  p_refresh_token text,
  p_expiry_date bigint
)
returns void
language plpgsql
security definer
as $$
begin
  insert into public.gmail_tokens (firebase_uid, access_token, refresh_token, expiry_date, updated_at)
  values (p_uid, p_access_token, p_refresh_token, p_expiry_date, now())
  on conflict (firebase_uid)
  do update set
    access_token = excluded.access_token,
    refresh_token = coalesce(excluded.refresh_token, public.gmail_tokens.refresh_token),
    expiry_date = excluded.expiry_date,
    updated_at = now();
end;
$$;

-- 19. Grant Schema Privileges
grant usage on schema public to anon, authenticated, service_role;
grant all on all tables in schema public to anon, authenticated, service_role;
grant all on all sequences in schema public to anon, authenticated, service_role;
grant all on all routines in schema public to anon, authenticated, service_role;

alter default privileges in schema public grant all on tables to anon, authenticated, service_role;
alter default privileges in schema public grant all on sequences to anon, authenticated, service_role;
alter default privileges in schema public grant all on routines to anon, authenticated, service_role;

-- 20. Row Level Security (RLS) Setup for All Tables
-- User Profiles
alter table if exists public.user_profiles enable row level security;
drop policy if exists "Allow all access to user_profiles" on public.user_profiles;
create policy "Allow all access to user_profiles"
  on public.user_profiles for all
  to anon, authenticated, service_role
  using (true) with check (true);

-- Transactions
alter table if exists public.transactions enable row level security;
drop policy if exists "Allow all access to transactions" on public.transactions;
create policy "Allow all access to transactions"
  on public.transactions for all
  to anon, authenticated, service_role
  using (true) with check (true);

-- Budgets
alter table if exists public.budgets enable row level security;
drop policy if exists "Allow all access to budgets" on public.budgets;
create policy "Allow all access to budgets"
  on public.budgets for all
  to anon, authenticated, service_role
  using (true) with check (true);

-- Savings Goals
alter table if exists public.savings_goals enable row level security;
drop policy if exists "Allow all access to savings_goals" on public.savings_goals;
create policy "Allow all access to savings_goals"
  on public.savings_goals for all
  to anon, authenticated, service_role
  using (true) with check (true);

-- SIP Plans
alter table if exists public.sip_plans enable row level security;
drop policy if exists "Allow all access to sip_plans" on public.sip_plans;
create policy "Allow all access to sip_plans"
  on public.sip_plans for all
  to anon, authenticated, service_role
  using (true) with check (true);

-- Manual Investments
alter table if exists public.manual_investments enable row level security;
drop policy if exists "Allow all access to manual_investments" on public.manual_investments;
create policy "Allow all access to manual_investments"
  on public.manual_investments for all
  to anon, authenticated, service_role
  using (true) with check (true);

-- Recurring Transactions
alter table if exists public.recurring_transactions enable row level security;
drop policy if exists "Allow all access to recurring_transactions" on public.recurring_transactions;
create policy "Allow all access to recurring_transactions"
  on public.recurring_transactions for all
  to anon, authenticated, service_role
  using (true) with check (true);

-- Recurring Savings
alter table if exists public.recurring_savings enable row level security;
drop policy if exists "Allow all access to recurring_savings" on public.recurring_savings;
create policy "Allow all access to recurring_savings"
  on public.recurring_savings for all
  to anon, authenticated, service_role
  using (true) with check (true);

-- Notifications
alter table if exists public.notifications enable row level security;
drop policy if exists "Allow all access to notifications" on public.notifications;
create policy "Allow all access to notifications"
  on public.notifications for all
  to anon, authenticated, service_role
  using (true) with check (true);

-- Alert Rules
alter table if exists public.alert_rules enable row level security;
drop policy if exists "Allow all access to alert_rules" on public.alert_rules;
create policy "Allow all access to alert_rules"
  on public.alert_rules for all
  to anon, authenticated, service_role
  using (true) with check (true);

-- Merchant Memory
alter table if exists public.merchant_memory enable row level security;
drop policy if exists "Allow all access to merchant_memory" on public.merchant_memory;
create policy "Allow all access to merchant_memory"
  on public.merchant_memory for all
  to anon, authenticated, service_role
  using (true) with check (true);

-- Yearly Budget Summary
alter table if exists public.yearly_budget_summary enable row level security;
drop policy if exists "Allow all access to yearly_budget_summary" on public.yearly_budget_summary;
create policy "Allow all access to yearly_budget_summary"
  on public.yearly_budget_summary for all
  to anon, authenticated, service_role
  using (true) with check (true);

-- Gmail Tokens
alter table if exists public.gmail_tokens enable row level security;
drop policy if exists "Allow all access to gmail_tokens" on public.gmail_tokens;
create policy "Allow all access to gmail_tokens"
  on public.gmail_tokens for all
  to anon, authenticated, service_role
  using (true) with check (true);

-- Processed Emails
alter table if exists public.processed_emails enable row level security;
drop policy if exists "Allow all access to processed_emails" on public.processed_emails;
create policy "Allow all access to processed_emails"
  on public.processed_emails for all
  to anon, authenticated, service_role
  using (true) with check (true);

-- Chat Sessions
alter table if exists public.chat_sessions enable row level security;
drop policy if exists "Allow all access to chat_sessions" on public.chat_sessions;
create policy "Allow all access to chat_sessions"
  on public.chat_sessions for all
  to anon, authenticated, service_role
  using (true) with check (true);

-- Chat Messages
alter table if exists public.chat_messages enable row level security;
drop policy if exists "Allow all access to chat_messages" on public.chat_messages;
create policy "Allow all access to chat_messages"
  on public.chat_messages for all
  to anon, authenticated, service_role
  using (true) with check (true);

-- 21. Avatars Storage Bucket & Policies
insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do update set public = true;

drop policy if exists "Public Access for Avatars" on storage.objects;
drop policy if exists "Allow Avatar Uploads" on storage.objects;
drop policy if exists "Allow Avatar Updates" on storage.objects;
drop policy if exists "Allow Avatar Deletes" on storage.objects;
drop policy if exists "Allow all for avatars" on storage.objects;

create policy "Allow all for avatars"
  on storage.objects for all
  to anon, authenticated, service_role
  using (bucket_id = 'avatars')
  with check (bucket_id = 'avatars');

-- 22. Dynamic Safety Net (Ensures every public table is secured & accessible)
do $$
declare
  t text;
begin
  for t in (
    select tablename 
    from pg_tables 
    where schemaname = 'public'
  ) loop
    execute format('alter table public.%I enable row level security;', t);
    execute format('drop policy if exists "Auto allow all on %I" on public.%I;', t, t);
    execute format('create policy "Auto allow all on %I" on public.%I for all to anon, authenticated, service_role using (true) with check (true);', t, t);
  end loop;
end $$;
