// src/context/LanguageContext.tsx
import { createContext, useContext, useState, type ReactNode } from "react";

export type Language = "en" | "hi";

interface LanguageContextValue {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

// ─── Translations ─────────────────────────────────────────────────────────────
export const translations: Record<string, Record<Language, string>> = {
  // ── Navigation / Sidebar ──
  "nav.dashboard":              { en: "Dashboard",                hi: "डैशबोर्ड" },
  "nav.udhaarBook":             { en: "Udhaar Book",              hi: "उधार बही" },
  "nav.khata":                  { en: "Customer Khata (Udhaar)",  hi: "ग्राहक खाता (उधार)" },
  "nav.addTransactionBusiness": { en: "Add Transaction",          hi: "लेन-देन जोड़ें" },
  "nav.transactionHistory":     { en: "Transaction History",      hi: "लेन-देन इतिहास" },
  "nav.cashBook":               { en: "Transaction History",      hi: "लेन-देन इतिहास" },
  "nav.reportsBusiness":        { en: "Report and Analytics",     hi: "रिपोर्ट और एनालिटिक्स" },
  "nav.businessGrowth":         { en: "Business Growth Hub",      hi: "बिजनेस ग्रोथ हब" },
  "nav.voiceCapture":           { en: "Add Transaction",          hi: "लेन-देन जोड़ें" },
  "nav.transaction":            { en: "Transactions",             hi: "लेन-देन" },
  "nav.addExpensePersonal":     { en: "Add Expense/Income",       hi: "खर्च / आय जोड़ें" },
  "nav.budget":                 { en: "Budget & Investment",      hi: "बजट और निवेश" },
  "nav.budgetPersonal":         { en: "Budgets & Wealth Goals",   hi: "बजट और बचत लक्ष्य" },
  "nav.reports":                { en: "Reports",                  hi: "रिपोर्ट" },
  "nav.reportsPersonal":        { en: "Spending Reports",         hi: "खर्च रिपोर्ट" },
  "nav.aiAssistant":            { en: "AI Assistant",             hi: "AI सहायक" },
  "nav.moneyGrowth":            { en: "Money Growth",             hi: "पैसे की बढ़त" },
  "nav.settings":               { en: "Settings",                 hi: "सेटिंग्स" },
  "nav.notifications":          { en: "Notifications",            hi: "सूचनाएं" },

  // ── AI Assistant & Previous Chats ──
  "ai.title":                   { en: "AI Assistant",             hi: "एआई सहायक" },
  "ai.titleBusiness":           { en: "Business AI Assistant",    hi: "बिजनेस एआई सहायक" },
  "ai.previousChats":           { en: "Previous Chats",           hi: "पिछली चैट" },
  "ai.pastConversations":       { en: "Past Conversations",       hi: "पिछली बातचीत" },
  "ai.newChat":                 { en: "New Chat",                 hi: "नई चैट" },
  "ai.clearChat":               { en: "Clear Chat",               hi: "चैट साफ़ करें" },
  "ai.searchChats":             { en: "Search your chats...",     hi: "अपनी चैट खोजें..." },
  "ai.noChats":                 { en: "No previous chats found",  hi: "कोई पिछली चैट नहीं मिली" },
  "ai.deleteChatConfirm":       { en: "Delete this conversation? This cannot be undone.", hi: "क्या आप यह बातचीत हटाना चाहते हैं? इसे वापस नहीं लाया जा सकेगा।" },

  // ── Header ──
  "header.yourChats":     { en: "Your Chats",         hi: "आपकी चैट" },

  // ── Dashboard Home ──
  "home.greeting.morning":  { en: "Good morning",     hi: "सुप्रभात" },
  "home.greeting.afternoon":{ en: "Good afternoon",   hi: "नमस्ते" },
  "home.greeting.evening":  { en: "Good evening",     hi: "शुभ संध्या" },
  "home.greeting.night":    { en: "Good night",       hi: "शुभ रात्रि" },
  "home.subtitle":          { en: "Wrapping up the day's transactions for a clear financial overview.", hi: "आज के लेन-देन का स्पष्ट वित्तीय अवलोकन।" },
  "home.addTransaction":    { en: "ADD TRANSACTION",  hi: "लेन-देन जोड़ें" },
  "home.speakReviewSave":   { en: "Speak → Review → Save", hi: "बोलें → देखें → सेव करें" },
  "home.voiceHint":         { en: "Say what happened in Hindi or English, review details, and save directly to your ledger.", hi: "हिंदी या अंग्रेजी में बोलें, विवरण देखें और सीधे खाते में सेव करें।" },
  "home.recordByVoice":     { en: "Record by Voice",  hi: "आवाज़ से रिकॉर्ड करें" },
  "home.fullView":          { en: "Full View",        hi: "पूर्ण दृश्य" },
  "home.smartSuggestions":  { en: "Smart Suggestions", hi: "स्मार्ट सुझाव" },
  "home.smartSuggestionsDesc": { en: "Personalised tips based on your spending", hi: "आपके खर्च के आधार पर व्यक्तिगत सुझाव" },
  "home.netDeficit":        { en: "Net Deficit",      hi: "कुल घाटा" },
  "home.netSurplus":        { en: "Net Surplus",      hi: "कुल बचत" },
  "home.totalExpenses":     { en: "Total Expenses",   hi: "कुल खर्च" },
  "home.totalIncome":       { en: "Total Income",     hi: "कुल आय" },
  "home.savingsRate":       { en: "Savings Rate",     hi: "बचत दर" },

  // ── Add Transaction Page ──
  "voice.title":            { en: "Add Transaction",   hi: "लेन-देन जोड़ें" },
  "voice.reviewEntry":      { en: "REVIEW ENTRY",     hi: "प्रविष्टि की समीक्षा" },
  "voice.reviewBeforeSaving": { en: "Review before saving", hi: "सेव करने से पहले देखें" },
  "voice.recordAgain":      { en: "Record again",     hi: "फिर से रिकॉर्ड करें" },
  "voice.credit":           { en: "Credit (Money Received / Inflow)", hi: "जमा (पैसा मिला)" },
  "voice.debit":            { en: "Debit (Money Paid / Udhaar)", hi: "नामे (पैसा दिया / उधार)" },
  "voice.customerName":     { en: "Customer / Party Name", hi: "ग्राहक / पार्टी का नाम" },
  "voice.amount":           { en: "Amount (₹)",       hi: "राशि (₹)" },
  "voice.category":         { en: "Category",         hi: "श्रेणी" },
  "voice.paymentMethod":    { en: "Payment Method",   hi: "भुगतान का तरीका" },
  "voice.transactionDate":  { en: "Transaction Date", hi: "लेन-देन की तारीख" },
  "voice.cancel":           { en: "Cancel",           hi: "रद्द करें" },
  "voice.saveWithConfidence": { en: "Save with confidence", hi: "विश्वास के साथ सेव करें" },
  "voice.backToOverview":   { en: "Back to overview", hi: "वापस जाएं" },
  "voice.voiceFirst":       { en: "Voice-first capture", hi: "आवाज़ से दर्ज करें" },
  "voice.reviewEntry2":     { en: "Review entry",     hi: "प्रविष्टि देखें" },
  "voice.heard":            { en: "Heard",            hi: "सुना" },
  "voice.businessMode":     { en: "Business Mode",    hi: "व्यवसाय मोड" },
  "voice.personalMode":     { en: "Personal Mode",    hi: "व्यक्तिगत मोड" },

  // ── Transactions Page ──
  "tx.title":               { en: "Transactions",     hi: "लेन-देन" },
  "tx.addNew":              { en: "Add New",          hi: "नया जोड़ें" },
  "tx.search":              { en: "Search transactions...", hi: "लेन-देन खोजें..." },
  "tx.filter":              { en: "Filter",           hi: "फ़िल्टर" },
  "tx.description":         { en: "Description",      hi: "विवरण" },

  // ── Reports Page ──
  "reports.monthly":        { en: "Monthly",          hi: "मासिक" },
  "reports.weekly":         { en: "Weekly",           hi: "साप्ताहिक" },
  "reports.yearly":         { en: "Yearly",           hi: "वार्षिक" },

  // ── AI Assistant ──
  "ai.title":               { en: "AI Assistant",     hi: "AI सहायक" },
  "ai.placeholder":         { en: "Ask about your finances...", hi: "अपने वित्त के बारे में पूछें..." },
  "ai.send":                { en: "Send",             hi: "भेजें" },
  "ai.smartSuggestions":    { en: "Smart Suggestions", hi: "स्मार्ट सुझाव" },
  "ai.smartSuggestionsDesc":{ en: "Personalised tips based on your spending", hi: "आपके खर्च के आधार पर व्यक्तिगत सुझाव" },
  "ai.generating":          { en: "Generating",       hi: "तैयार हो रहा है" },
  "ai.live":                { en: "Live",             hi: "लाइव" },
  "ai.refresh":             { en: "Refresh",          hi: "रिफ्रेश" },
  "ai.disclaimer":          { en: "AI-generated suggestions — not financial advice.", hi: "AI द्वारा उत्पन्न सुझाव — वित्तीय सलाह नहीं।" },
  "ai.chatWithAI":          { en: "Chat with AI",    hi: "AI से बात करें" },

  // ── Section Cards ──
  "cards.totalBalance":     { en: "Total Balance",    hi: "कुल शेष" },
  "cards.deficit":          { en: "Deficit",          hi: "घाटा" },
  "cards.live":             { en: "Live",             hi: "लाइव" },
  "cards.expensesExceedIncome": { en: "Expenses exceed income", hi: "खर्च आय से अधिक है" },
  "cards.currentBalance":   { en: "Current available balance", hi: "वर्तमान उपलब्ध शेष" },
  "cards.deficitOf":        { en: "Deficit of",       hi: "घाटा" },
  "cards.acrossAccounts":   { en: "Across all linked accounts", hi: "सभी खातों में" },
  "cards.spendingAcross":   { en: "Spending across transactions", hi: "लेन-देन में खर्च" },
  "cards.calculatedFromDebit": { en: "Calculated from debit payments", hi: "नामे भुगतान से गणना" },
  "cards.moneyReceived":    { en: "Money received",   hi: "पैसा मिला" },
  "cards.fromSalary":       { en: "From salary, transfers and income", hi: "वेतन, ट्रांसफर और आय से" },
  "cards.saving":           { en: "Saving",           hi: "बचत" },
  "cards.percentageSaved":  { en: "Percentage of income saved", hi: "आय का बचाया गया प्रतिशत" },
  "cards.calculatedFromMetrics": { en: "Calculated from centralized metrics engine", hi: "केंद्रीय मेट्रिक्स इंजन से गणना" },
  "cards.businessBalance":  { en: "Net Cash Flow",    hi: "शुद्ध नकदी प्रवाह" },
  "cards.businessExpenses": { en: "Business Outflows / Udhaar", hi: "व्यापारिक खर्च / दिया गया उधार" },
  "cards.businessIncome":   { en: "Sales & Collections", hi: "कुल बिक्री व जमा" },
  "cards.receivables":      { en: "Outstanding Receivables", hi: "कुल बकाया (उधार)" },
  "cards.receivablesDesc":  { en: "Pending from customers in Khata", hi: "खाते में ग्राहकों से लेना बाकी" },
  "cards.cashFlowDesc":     { en: "Inflows minus outflows", hi: "कुल आवक घटाव जावक" },
  "cards.businessDebitDesc":{ en: "Credit given & expenses", hi: "ग्राहकों को दिया उधार व व्यापारिक खर्च" },
  "cards.businessCreditDesc":{ en: "Sales & customer payments", hi: "नकद/UPI बिक्री व ग्राहकों से जमा" },

  // ── Quick Links ──
  "quicklinks.title":       { en: "Quick Actions",   hi: "त्वरित क्रियाएं" },
  "quicklinks.aiDesc":      { en: "Ask anything about your finances", hi: "वित्त के बारे में कुछ भी पूछें" },
  "quicklinks.txDesc":      { en: "Manage your income & expenses", hi: "आय और खर्च प्रबंधित करें" },
  "quicklinks.budgets":     { en: "Budgets",          hi: "बजट" },
  "quicklinks.budgetsDesc": { en: "Set and track your limits", hi: "अपनी सीमाएं निर्धारित करें" },
  "quicklinks.khata":       { en: "Customer Khata",   hi: "ग्राहक खाता" },
  "quicklinks.khataDesc":   { en: "Track customer credit & Udhaar", hi: "ग्राहक उधार और हिसाब ट्रैक करें" },
  "quicklinks.reportsDesc": { en: "Deep dive into your analytics", hi: "अपने विश्लेषण में गहराई से जाएं" },

  // ── Common ──
  "common.save":            { en: "Save",             hi: "सेव करें" },
  "common.cancel":          { en: "Cancel",           hi: "रद्द करें" },
  "common.edit":            { en: "Edit",             hi: "संपादित करें" },
  "common.delete":          { en: "Delete",           hi: "हटाएं" },
  "common.add":             { en: "Add",              hi: "जोड़ें" },
  "common.search":          { en: "Search",           hi: "खोजें" },
  "common.loading":         { en: "Loading...",       hi: "लोड हो रहा है..." },
  "common.saving":          { en: "Saving...",        hi: "सेव किया जा रहा है..." },
  "common.deleting":        { en: "Deleting...",      hi: "हटाया जा रहा है..." },
  "common.confirmDelete":   { en: "Are you sure?",    hi: "क्या आप निश्चित हैं?" },
  "common.cannotUndo":      { en: "This action cannot be undone.", hi: "यह कार्रवाई वापस नहीं की जा सकती।" },
  "common.viewDetails":     { en: "View Details",     hi: "विवरण देखें" },
  "common.comingSoon":      { en: "Coming soon!",     hi: "जल्द आ रहा है!" },
  "common.online":          { en: "Online",           hi: "ऑनलाइन" },
  "common.today":           { en: "Today",            hi: "आज" },
  "common.yesterday":       { en: "Yesterday",        hi: "कल" },
  "common.business":        { en: "Business",         hi: "व्यवसाय" },
  "common.personal":        { en: "Personal",         hi: "व्यक्तिगत" },
  "common.noData":          { en: "No data available", hi: "कोई डेटा उपलब्ध नहीं" },
  "common.error":           { en: "Something went wrong", hi: "कुछ गलत हो गया" },

  // ── Months ──
  "month.january":          { en: "January",          hi: "जनवरी" },
  "month.february":         { en: "February",         hi: "फ़रवरी" },
  "month.march":            { en: "March",            hi: "मार्च" },
  "month.april":            { en: "April",            hi: "अप्रैल" },
  "month.may":              { en: "May",              hi: "मई" },
  "month.june":             { en: "June",             hi: "जून" },
  "month.july":             { en: "July",             hi: "जुलाई" },
  "month.august":           { en: "August",           hi: "अगस्त" },
  "month.september":        { en: "September",        hi: "सितंबर" },
  "month.october":          { en: "October",          hi: "अक्टूबर" },
  "month.november":         { en: "November",         hi: "नवंबर" },
  "month.december":         { en: "December",         hi: "दिसंबर" },

  // ── Transactions page extras ──
  "tx.transactionsFound":   { en: "transactions found", hi: "लेन-देन मिले" },
  "tx.mode":                { en: "Mode",             hi: "मोड" },
  "tx.autoflow":            { en: "AutoFlow",         hi: "ऑटोफ्लो" },
  "tx.recurringRules":      { en: "recurring rules",  hi: "आवर्ती नियम" },
  "tx.loadingRules":        { en: "Loading autopay rules…", hi: "ऑटोपे नियम लोड हो रहे हैं..." },
  "tx.searchPlaceholder":   { en: "Search transactions...", hi: "लेन-देन खोजें..." },
  "tx.category":            { en: "Category",         hi: "श्रेणी" },
  "tx.allCategories":       { en: "All Categories",   hi: "सभी श्रेणियां" },
  "tx.allTypes":            { en: "All Types",        hi: "सभी प्रकार" },
  "tx.status":              { en: "Status",           hi: "स्थिति" },
  "tx.allStatuses":         { en: "All Statuses",     hi: "सभी स्थितियां" },
  "tx.completed":           { en: "Completed",        hi: "पूरा हुआ" },
  "tx.pending":             { en: "Pending",          hi: "लंबित" },
  "tx.method":              { en: "Method",           hi: "तरीका" },
  "tx.allMethods":          { en: "All Methods",      hi: "सभी तरीके" },
  "tx.fromDate":            { en: "From date",        hi: "प्रारंभ तिथि" },
  "tx.toDate":              { en: "To date",          hi: "अंतिम तिथि" },
  "tx.clear":               { en: "Clear",            hi: "साफ़ करें" },
  "tx.clearAll":            { en: "Clear all",        hi: "सभी साफ़ करें" },
  "tx.transaction":         { en: "Transaction",      hi: "लेन-देन" },
  "tx.actions":             { en: "Actions",          hi: "कार्रवाई" },
  "tx.noResults":           { en: "No results.",      hi: "कोई परिणाम नहीं।" },
  "tx.rowsPerPage":         { en: "Rows per page",    hi: "प्रति पृष्ठ पंक्तियाँ" },
  "tx.pageOf":              { en: "Page",             hi: "पृष्ठ" },
  "tx.of":                  { en: "of",               hi: "में से" },
  "tx.frequency":           { en: "Frequency",        hi: "आवृत्ति" },
  "tx.activeRules":         { en: "Active Rules",     hi: "सक्रिय नियम" },
  "tx.total":               { en: "total",            hi: "कुल" },
  "tx.monthlyOutflow":      { en: "Monthly Outflow",  hi: "मासिक खर्च" },
  "tx.estimatedDebitMonth": { en: "Estimated debit / month", hi: "अनुमानित डेबिट / माह" },
  "tx.monthlyInflow":       { en: "Monthly Inflow",   hi: "मासिक आय" },
  "tx.estimatedCreditMonth":{ en: "Estimated credit / month", hi: "अनुमानित क्रेडिट / माह" },
  "tx.dueThisWeek":         { en: "Due This Week",    hi: "इस सप्ताह देय" },
  "tx.runningIn7Days":      { en: "Transactions running in 7 days", hi: "7 दिनों में चलने वाले लेन-देन" },
  "tx.startDate":           { en: "Start Date",       hi: "प्रारंभ तिथि" },
  "tx.endDate":             { en: "End Date",         hi: "अंतिम तिथि" },
  "tx.optional":            { en: "optional",         hi: "वैकल्पिक" },
  "tx.nextRun":             { en: "Next Run",         hi: "अगला रन" },
  "tx.active":              { en: "Active",           hi: "सक्रिय" },
  "tx.noRecurringRules":    { en: "No autopay rules yet. Add one to get started!", hi: "अभी तक कोई ऑटोपे नियम नहीं है। शुरू करने के लिए एक जोड़ें!" },
  "tx.pause":               { en: "Pause",            hi: "रोकें" },
  "tx.resume":              { en: "Resume",           hi: "फिर से शुरू करें" },
  "tx.autopayRuleDetails":  { en: "Autopay rule details", hi: "ऑटोपे नियम विवरण" },
  "tx.noEndDate":           { en: "No end date",      hi: "कोई अंतिम तिथि नहीं" },
  "tx.paused":              { en: "Paused",           hi: "रोका गया" },

  // ── Budgets ──
  "budget.subtitle":        { en: "Track your budget, goals, SIPs, investments, and growth projections", hi: "अपने बजट, लक्ष्यों, एसआईपी, निवेश और विकास अनुमानों को ट्रैक करें" },
  "budget.totalSaved":      { en: "Total Saved",      hi: "कुल बचत" },
  "budget.totalInvested":   { en: "Total Invested",   hi: "कुल निवेश" },
  "budget.totalTarget":     { en: "Total Target",     hi: "कुल लक्ष्य" },
  "budget.tabBudget":       { en: "Budget",           hi: "बजट" },
  "budget.tabGoals":        { en: "Goals",            hi: "लक्ष्य" },
  "budget.tabSIP":          { en: "SIP",              hi: "एसआईपी (SIP)" },
  "budget.tabPortfolio":    { en: "Portfolio",        hi: "पोर्टफोलियो" },
  "budget.tabInsights":     { en: "Insights",         hi: "अंतर्दृष्टि" },
  "budget.tabProjection":   { en: "Projection",       hi: "अनुमान" },
  "budget.loadingSavings":  { en: "Loading your savings data...", hi: "बचत डेटा लोड हो रहा है..." },
  "budget.loadingBudgets":  { en: "Loading budgets…", hi: "बजट लोड हो रहे हैं..." },
  "budget.editTotalBudget": { en: "Edit total budget", hi: "कुल बजट संपादित करें" },
  "budget.clearAutoSum":    { en: "Clear to auto-sum categories", hi: "श्रेणियों का स्वतः-योग करने के लिए साफ़ करें" },
  "budget.overrideSum":     { en: "Overrides sum of categories", hi: "श्रेणियों के योग को ओवरराइड करता है" },
  "budget.custom":          { en: "(custom)",         hi: "(कस्टम)" },
  "budget.totalSpent":      { en: "Total Spent",      hi: "कुल खर्च" },
  "budget.overBudget":      { en: "Over Budget",      hi: "बजट से अधिक" },
  "budget.category":        { en: "category",         hi: "श्रेणी" },
  "budget.categories":      { en: "categories",       hi: "श्रेणियाँ" },
  "budget.healthScore":     { en: "Health Score",     hi: "स्वास्थ्य स्कोर" },
  "budget.overallSpending": { en: "Overall spending", hi: "कुल खर्च" },
  "budget.used":            { en: "used",             hi: "इस्तेमाल किया गया" },
  "budget.manualCap":       { en: "Manual cap",       hi: "मैन्युअल कैप" },
  "budget.categoriesSum":   { en: "Categories sum",   hi: "श्रेणियों का योग" },
  "budget.enterValidAmount":{ en: "Enter a valid amount", hi: "वैध राशि दर्ज करें" },
  "budget.monthly":         { en: "Monthly",          hi: "मासिक" },
  "budget.3months":         { en: "3 Months",         hi: "3 महीने" },
  "budget.6months":         { en: "6 Months",         hi: "6 महीने" },
  "budget.12months":        { en: "12 Months",        hi: "12 महीने" },
  "budget.yearly":          { en: "Yearly",           hi: "वार्षिक" },
  "budget.timeless":        { en: "Timeless",         hi: "कालातीत" },
  "budget.durationGuard":   { en: "Duration guard",   hi: "अवधि गार्ड" },
  "budget.over":            { en: "over",             hi: "अधिक" },
  "budget.left":            { en: "left",             hi: "शेष" },
  "budget.definedAt":       { en: "Budget defined at", hi: "पर निर्धारित बजट" },
  "budget.noSpendingYet":   { en: "— no spending recorded yet", hi: "— अभी तक कोई खर्च दर्ज नहीं किया गया" },
  "budget.noBudgets":       { en: "No budgets set for this month. Start from a template.", hi: "इस महीने के लिए कोई बजट निर्धारित नहीं है। टेम्प्लेट से शुरू करें।" },
  "budget.use":             { en: "Use",              hi: "उपयोग करें" },
  "budget.templateFailed":  { en: "Template failed for", hi: "के लिए टेम्प्लेट विफल रहा" },
  "budget.items":           { en: "item(s).",         hi: "आइटम।" },
  "budget.templateApplied": { en: "Template applied.", hi: "टेम्प्लेट लागू किया गया।" },
  "budget.setBudget":       { en: "Set Budget",       hi: "बजट सेट करें" },
  "budget.setSpendingLimit":{ en: "Set a spending limit for a category.", hi: "किसी श्रेणी के लिए खर्च सीमा निर्धारित करें।" },
  "budget.alreadyBudgeted": { en: "Already budgeted", hi: "पहले से बजट किया गया" },
  "budget.yourCategories":  { en: "Your categories",  hi: "आपकी श्रेणियाँ" },
  "budget.otherCustomName": { en: "Other (custom name)", hi: "अन्य (कस्टम नाम)" },
  "budget.categoryName":    { en: "Category Name",    hi: "श्रेणी का नाम" },
  "budget.spendingLimit":   { en: "Spending Limit (₹)", hi: "खर्च सीमा (₹)" },
  "budget.duration":        { en: "Duration",         hi: "अवधि" },
  "budget.timelessDesc":    { en: "Budget applies until manually deleted.", hi: "बजट मैन्युअल रूप से हटाए जाने तक लागू रहता है।" },
  "budget.monthlyDesc":     { en: "Budget resets each month.", hi: "बजट हर महीने रीसेट होता है।" },
  "budget.spansMonths":     { en: "Budget spans",     hi: "बजट" },
  "budget.fromCreation":    { en: "months from creation.", hi: "महीने तक चलता है।" },
  "budget.editBudget":      { en: "Edit Budget",      hi: "बजट संपादित करें" },
  "budget.updateSpendingLimit": { en: "Update the spending limit for this category.", hi: "इस श्रेणी के लिए खर्च सीमा अपडेट करें।" },
  "budget.current":         { en: "Current",          hi: "वर्तमान" },
  "budget.12monthsLabel":   { en: "12 Months (1 Year)", hi: "12 महीने (1 वर्ष)" },
  "budget.deleteBudget":    { en: "Delete budget",    hi: "बजट हटाएं" },
  "budget.deleteDesc":      { en: "This will permanently remove the budget and cannot be undone.", hi: "यह बजट को स्थायी रूप से हटा देगा और इसे वापस नहीं किया जा सकता।" },
  "budget.deleteNote":      { en: "Deleting this budget will not affect your transaction history. Only the spending limit will be removed.", hi: "इस बजट को हटाने से आपके लेन-देन के इतिहास पर कोई प्रभाव नहीं पड़ेगा। केवल खर्च सीमा हटा दी जाएगी।" },
  "budget.deleting":        { en: "Deleting...",      hi: "हटाया जा रहा है..." },

  // ── Savings & Goals ──
  "savings.goalName":       { en: "Goal Name",        hi: "लक्ष्य का नाम" },
  "savings.editGoal":       { en: "Edit Goal",        hi: "लक्ष्य संपादित करें" },
  "savings.addSavingsGoal": { en: "Add Savings Goal", hi: "बचत लक्ष्य जोड़ें" },
  "savings.targetAmount":   { en: "Target Amount (₹)", hi: "लक्ष्य राशि (₹)" },
  "savings.alreadySaved":   { en: "Already Saved (₹)", hi: "पहले से ही बचाया गया (₹)" },
  "savings.deadline":       { en: "Deadline (optional)", hi: "अंतिम तिथि (वैकल्पिक)" },
  "savings.timeless":       { en: "∞ Timeless",       hi: "∞ कालातीत" },
  "savings.clearDate":      { en: "Clear date",       hi: "तिथि साफ़ करें" },
  "savings.noDeadline":     { en: "∞ No deadline — this goal runs forever", hi: "∞ कोई अंतिम तिथि नहीं — यह लक्ष्य हमेशा चलता है" },
  "savings.color":          { en: "Color",            hi: "रंग" },
  "savings.goalNameRequired":{ en: "Goal name is required.", hi: "लक्ष्य का नाम आवश्यक है।" },
  "savings.validTargetAmount":{ en: "Enter a valid target amount.", hi: "वैध लक्ष्य राशि दर्ज करें।" },
  "savings.targetAmountGreaterThanZero": { en: "Target amount must be greater than 0.", hi: "लक्ष्य राशि 0 से अधिक होनी चाहिए।" },
  "savings.savedExceedsTarget": { en: "Saved amount cannot exceed target amount.", hi: "बचाई गई राशि लक्ष्य राशि से अधिक नहीं हो सकती।" },
  "savings.addGoal":        { en: "Add Goal",         hi: "लक्ष्य जोड़ें" },
  "savings.addInvestment":  { en: "Add Investment",   hi: "निवेश जोड़ें" },
  "savings.editInvestment": { en: "Edit Investment",  hi: "निवेश संपादित करें" },
  "savings.investmentName": { en: "Investment Name",  hi: "निवेश का नाम" },
  "savings.investmentNameRequired": { en: "Investment name is required.", hi: "निवेश का नाम आवश्यक है।" },
  "savings.investmentType": { en: "Investment Type",  hi: "निवेश का प्रकार" },
  "savings.priceBased":     { en: "Price Based",      hi: "मूल्य आधारित" },
  "savings.amountBased":    { en: "Amount Based",     hi: "राशि आधारित" },
  "savings.quantityUnits":  { en: "Quantity / Units", hi: "मात्रा / इकाइयाँ" },
  "savings.validQuantity":  { en: "Enter a valid quantity.", hi: "वैध मात्रा दर्ज करें।" },
  "savings.buyPrice":       { en: "Buy Price per Unit (₹)", hi: "खरीद मूल्य प्रति इकाई (₹)" },
  "savings.validBuyPrice":  { en: "Enter a valid buy price.", hi: "वैध खरीद मूल्य दर्ज करें।" },
  "savings.dateOfPurchase": { en: "Date of Purchase", hi: "खरीद की तिथि" },
  "savings.currentPrice":   { en: "Current Price per Unit (₹)", hi: "वर्तमान मूल्य प्रति इकाई (₹)" },
  "savings.optional":       { en: "optional",         hi: "वैकल्पिक" },
  "savings.leaveBlank":     { en: "Leave blank if unknown", hi: "यदि अज्ञात हो तो खाली छोड़ दें" },
  "savings.amountInvested": { en: "Amount Invested (₹)", hi: "निवेश की गई राशि (₹)" },
  "savings.validAmountInvested": { en: "Enter a valid invested amount.", hi: "वैध निवेश राशि दर्ज करें।" },
  "savings.expectedAnnualReturn": { en: "Expected Annual Return (%)", hi: "अपेक्षित वार्षिक रिटर्न (%)" },
  "savings.expectedReturnRange": { en: "Expected return must be between 0% and 200%.", hi: "अपेक्षित रिटर्न 0% और 200% के बीच होना चाहिए।" },
  "savings.livePreview":    { en: "Live Preview",     hi: "लाइव पूर्वावलोकन" },
  "savings.totalInvested":  { en: "Total Invested",   hi: "कुल निवेश" },
  "savings.currentValue":   { en: "Current Value",    hi: "वर्तमान मूल्य" },
  "savings.pl":             { en: "P & L",            hi: "लाभ और हानि" },
  "savings.cagr":           { en: "CAGR",             hi: "सीएजीआर" },
  "savings.heldFor":        { en: "Held for",         hi: "के लिए आयोजित" },
  "savings.estimatedValue1yr": { en: "Estimated value after 1 year", hi: "1 वर्ष के बाद अनुमानित मूल्य" },
  "savings.months":         { en: "months",           hi: "महीने" },
  "savings.years":          { en: "years",            hi: "वर्ष" },
  "savings.pa":             { en: "p.a.",             hi: "प्रति वर्ष" },
  "savings.salary":         { en: "Salary",           hi: "वेतन" },
  "savings.investmentReturn": { en: "Investment Return", hi: "निवेश रिटर्न" },
  "savings.manualTransfer": { en: "Manual Transfer",  hi: "मैन्युअल स्थानांतरण" },
  "savings.cashback":       { en: "Cashback / Refund", hi: "कैशबैक / रिफंड" },
  "savings.freelance":      { en: "Freelance",        hi: "फ्रीलांस" },
  "savings.gift":           { en: "Gift / Bonus",     hi: "उपहार / बोनस" },
  "savings.validAmount":    { en: "Enter a valid amount greater than 0.", hi: "0 से अधिक वैध राशि दर्ज करें।" },
  "savings.addSavings":     { en: "Add Savings",      hi: "बचत जोड़ें" },
  "savings.quickAdd":       { en: "Quick Add",        hi: "त्वरित जोड़" },
  "savings.source":         { en: "Source",           hi: "स्रोत" },
  "savings.addTo":          { en: "Add To",           hi: "इसमें जोड़ें" },
  "savings.generalSavingsPool": { en: "General Savings Pool", hi: "सामान्य बचत पूल" },
  "savings.suggestedAllocateTo": { en: "Suggested: allocate to", hi: "सुझाव: इसमें आवंटित करें" },
  "savings.complete":       { en: "complete",         hi: "पूर्ण" },
  "savings.tapToSelect":    { en: "— tap to select",  hi: "— चुनने के लिए टैप करें" },
  "savings.impactPreview":  { en: "Impact Preview",   hi: "प्रभाव पूर्वावलोकन" },
  "savings.stillRemaining": { en: "still remaining",  hi: "अभी भी शेष" },
  "savings.thisWillCompleteYourGoal": { en: "This will complete your goal", hi: "यह आपके लक्ष्य को पूरा करेगा" },
  "savings.notesOptional":  { en: "Notes (optional)", hi: "नोट्स (वैकल्पिक)" },
  "savings.addSIPPlan":     { en: "Add SIP Plan",     hi: "SIP योजना जोड़ें" },
  "savings.editSIPPlan":    { en: "Edit SIP Plan",    hi: "SIP योजना संपादित करें" },
  "savings.monthlySIPAmount": { en: "Monthly SIP Amount (₹)", hi: "मासिक SIP राशि (₹)" },
  "savings.durationYears":  { en: "Duration (Years)", hi: "अवधि (वर्ष)" },
  "savings.startDate":      { en: "Start Date",       hi: "प्रारंभ तिथि" },
  "savings.estimatedReturns": { en: "Estimated returns", hi: "अनुमानित रिटर्न" },
  "savings.totalReturns":   { en: "Total Returns",    hi: "कुल रिटर्न" },
  "savings.finalValue":     { en: "Final Value",      hi: "अंतिम मूल्य" },
  "savings.validMonthlyAmount": { en: "Enter a valid monthly amount.", hi: "वैध मासिक राशि दर्ज करें।" },
  "savings.monthlyAmountGreaterThanZero": { en: "Monthly amount must be greater than 0.", hi: "मासिक राशि 0 से अधिक होनी चाहिए।" },
  "savings.validDuration":  { en: "Enter a valid duration.", hi: "वैध अवधि दर्ज करें।" },
  "savings.durationRange":  { en: "Duration must be between 1 and 40 years.", hi: "अवधि 1 और 40 वर्ष के बीच होनी चाहिए।" },
  "savings.expectedReturnRangeSIP": { en: "Expected return must be between 1% and 50%.", hi: "अपेक्षित रिटर्न 1% और 50% के बीच होना चाहिए।" },

  // ── Goals Tab ──
  "savings.goalsTitle":     { en: "Savings Goals",    hi: "बचत लक्ष्य" },
  "savings.goalsSubtitle":  { en: "Track progress toward your financial targets", hi: "अपने वित्तीय लक्ष्यों की प्रगति ट्रैक करें" },
  "savings.addSavingsBtn":  { en: "Add Savings",      hi: "बचत जोड़ें" },
  "savings.addGoalBtn":     { en: "Add Goal",         hi: "लक्ष्य जोड़ें" },
  "savings.noGoalsYet":     { en: "No savings goals yet.", hi: "अभी कोई बचत लक्ष्य नहीं है।" },
  "savings.createFirstGoal":{ en: "Create your first goal", hi: "अपना पहला लक्ष्य बनाएं" },
  "savings.daysOverdue":    { en: "days overdue",     hi: "दिन देर हो चुकी है" },
  "savings.dueToday":       { en: "Due today",        hi: "आज देय है" },
  "savings.daysLeft":       { en: "days left",        hi: "दिन बाकी हैं" },
  "savings.saved":          { en: "saved",            hi: "बचाया गया" },
  "savings.target":         { en: "target",           hi: "लक्ष्य" },
  "savings.remaining":      { en: "remaining",        hi: "बाकी" },
  "savings.goalAchieved":   { en: "🎉 Goal achieved!", hi: "🎉 लक्ष्य हासिल हुआ!" },
  "savings.addMoney":       { en: "Add Money",        hi: "पैसे जोड़ें" },
  "savings.deleteGoalTitle":{ en: "Delete Savings Goal?", hi: "बचत लक्ष्य हटाएं?" },
  "savings.deleteGoalDesc": { en: "This will permanently delete this goal and all its progress.", hi: "यह इस लक्ष्य और इसकी सारी प्रगति को स्थायी रूप से हटा देगा।" },
  "savings.loadingGoals":   { en: "Loading goals...", hi: "लक्ष्य लोड हो रहे हैं..." },

  // ── SIP Tab ──
  "sip.title":              { en: "SIP Plans",        hi: "एसआईपी योजनाएं" },
  "sip.subtitle":           { en: "Systematic Investment Plan tracker & calculator", hi: "व्यवस्थित निवेश योजना (SIP) ट्रैकर और कैलकुलेटर" },
  "sip.addSIP":             { en: "Add SIP",          hi: "एसआईपी जोड़ें" },
  "sip.totalMonthlySIP":    { en: "Total Monthly SIP", hi: "कुल मासिक SIP" },
  "sip.activePlans":        { en: "Active Plans",     hi: "सक्रिय योजनाएं" },
  "sip.combinedFV":         { en: "Combined Future Value", hi: "संयुक्त भविष्य मूल्य" },
  "sip.noPlansYet":         { en: "No SIP plans yet. Start investing systematically.", hi: "अभी तक कोई SIP योजना नहीं है। व्यवस्थित निवेश शुरू करें।" },
  "sip.createFirstSIP":     { en: "Create your first SIP", hi: "अपनी पहली SIP बनाएं" },
  "sip.active":             { en: "Active",           hi: "सक्रिय" },
  "sip.paused":             { en: "Paused",           hi: "रोका गया" },
  "sip.yr":                 { en: "yr",               hi: "वर्ष" },
  "sip.timeElapsed":        { en: "Time elapsed",     hi: "बीता हुआ समय" },
  "sip.invested":           { en: "Invested",         hi: "निवेश किया गया" },
  "sip.returns":            { en: "Returns",          hi: "रिटर्न" },
  "sip.finalValue":         { en: "Final Value",      hi: "अंतिम मूल्य" },
  "sip.started":            { en: "Started",          hi: "शुरू हुआ" },
  "sip.deleteTitle":        { en: "Delete SIP Plan?", hi: "SIP योजना हटाएं?" },
  "sip.deleteDesc":         { en: "This will permanently delete this SIP plan.", hi: "यह इस SIP योजना को स्थायी रूप से हटा देगा।" },
  "sip.loading":            { en: "Loading SIP plans...", hi: "SIP योजनाएं लोड हो रही हैं..." },

  // ── Portfolio Tab ──
  "portfolio.title":        { en: "Manual Portfolio", hi: "मैन्युअल पोर्टफोलियो" },
  "portfolio.subtitle":     { en: "Track and manage all your investments in one place", hi: "अपने सभी निवेशों को एक ही स्थान पर ट्रैक और प्रबंधित करें" },
  "portfolio.addInvestment":{ en: "Add Investment",   hi: "निवेश जोड़ें" },
  "portfolio.invested":     { en: "Invested",         hi: "निवेश किया गया" },
  "portfolio.holding":      { en: "holding",          hi: "होल्डिंग" },
  "portfolio.holdings":     { en: "holdings",         hi: "होल्डिंग्स" },
  "portfolio.currentValue": { en: "Current Value",    hi: "वर्तमान मूल्य" },
  "portfolio.estimated":    { en: "estimated",        hi: "अनुमानित" },
  "portfolio.totalPL":      { en: "Total P&L",        hi: "कुल लाभ/हानि" },
  "portfolio.overall":      { en: "overall",          hi: "कुल मिलाकर" },
  "portfolio.allocation":   { en: "Allocation by Asset Class", hi: "परिसंपत्ति वर्ग द्वारा आवंटन" },
  "portfolio.noInvestments":{ en: "No investments recorded yet", hi: "अभी तक कोई निवेश दर्ज नहीं किया गया" },
  "portfolio.noInvestmentsDesc": { en: "Add your first holding to begin tracking portfolio performance", hi: "पोर्टफोलियो प्रदर्शन ट्रैक करना शुरू करने के लिए अपनी पहली होल्डिंग जोड़ें" },
  "portfolio.addFirst":     { en: "Add your first investment", hi: "अपना पहला निवेश जोड़ें" },
  "portfolio.holdingsList": { en: "Holdings",         hi: "होल्डिंग्स" },
  "portfolio.shares":       { en: "shares",           hi: "शेयर" },
  "portfolio.bought":       { en: "bought",           hi: "खरीदा" },
  "portfolio.now":          { en: "now",              hi: "अब" },
  "portfolio.held":         { en: "held",             hi: "अवधि" },
  "portfolio.disclaimer":   { en: "Stock values are calculated from manually entered current prices. Non-stock values use compound interest based on expected annual return. Update current prices periodically for accuracy.", hi: "स्टॉक मूल्यों की गणना मैन्युअल रूप से दर्ज किए गए वर्तमान मूल्यों से की जाती है। गैर-स्टॉक मूल्य अपेक्षित वार्षिक रिटर्न के आधार पर चक्रवृद्धि ब्याज का उपयोग करते हैं।" },
  "portfolio.deleteTitle":  { en: "Delete Investment?", hi: "निवेश हटाएं?" },
  "portfolio.deleteDesc":   { en: "This will permanently remove this investment record from your portfolio.", hi: "यह इस निवेश रिकॉर्ड को आपके पोर्टफोलियो से स्थायी रूप से हटा देगा।" },
  "portfolio.loading":      { en: "Loading portfolio...", hi: "पोर्टफोलियो लोड हो रहा है..." },
  "portfolio.type.stocks":  { en: "Stocks",           hi: "शेयर (Stocks)" },
  "portfolio.type.mutual_fund": { en: "Mutual Fund",  hi: "म्यूचुअल फंड" },
  "portfolio.type.gold":    { en: "Gold",             hi: "सोना (Gold)" },
  "portfolio.type.fd":      { en: "Fixed Deposit",    hi: "सावधि जमा (FD)" },
  "portfolio.type.crypto":  { en: "Crypto",           hi: "क्रिप्टो" },
  "portfolio.type.ppf":     { en: "PPF",              hi: "पीपीएफ (PPF)" },
  "portfolio.type.nps":     { en: "NPS",              hi: "एनपीएस (NPS)" },
  "portfolio.type.etf":     { en: "ETF",              hi: "ईटीएफ (ETF)" },
  "portfolio.type.other":   { en: "Other",            hi: "अन्य" },

  // ── Khata / Counterparties ──
  "khata.title":             { en: "Khata",            hi: "खाता" },
  "khata.subtitle":          { en: "Customers, suppliers, and balances in one place.", hi: "ग्राहक, सप्लायर्स और बकाया एक ही स्थान पर।" },
  "khata.addParty":          { en: "Add Customer / Supplier", hi: "ग्राहक / सप्लायर जोड़ें" },
  "khata.addCustomerOrSupplier": { en: "Add Customer or Supplier", hi: "ग्राहक या सप्लायर जोड़ें" },
  "khata.totalToReceive":    { en: "Total to receive", hi: "कुल लेना है" },
  "khata.fromCustomers":     { en: "From customers",   hi: "ग्राहकों से" },
  "khata.totalToPay":        { en: "Total to pay",     hi: "कुल देना है" },
  "khata.toSuppliers":       { en: "To suppliers & wholesalers", hi: "सप्लायर्स और थोक विक्रेताओं को" },
  "khata.overdue":           { en: "Overdue",          hi: "अतिदेय (Overdue)" },
  "khata.followUp":          { en: "Requires payment follow-up", hi: "भुगतान अनुवर्ती आवश्यक" },
  "khata.searchPlaceholder": { en: "Search customer by name or phone...", hi: "नाम या फोन से खोजें..." },
  "khata.all":               { en: "All",              hi: "सभी" },
  "khata.customers":         { en: "Customers",        hi: "ग्राहक" },
  "khata.suppliers":         { en: "Suppliers",        hi: "सप्लायर्स" },
  "khata.youWillReceive":    { en: "You will receive", hi: "आपको मिलेगा" },
  "khata.youWillPay":        { en: "You will pay",     hi: "आपको देना है" },
  "khata.recordByVoice":     { en: "Record by voice",  hi: "आवाज़ से दर्ज करें" },
  "khata.addEntryManually":  { en: "Add Entry Manually", hi: "हाथ से दर्ज करें" },
  "khata.ledger":            { en: "Chronological Ledger", hi: "खाता बही इतिहास" },
  "khata.ledgerDesc":        { en: "Complete history of money received and credit given", hi: "प्राप्त पैसे और दिए गए उधार का पूरा इतिहास" },
  "khata.noTx":              { en: "No transactions recorded yet", hi: "अभी तक कोई लेन-देन दर्ज नहीं है" },
  "khata.noTxDesc":          { en: "Record your first transaction by voice or click \"Add Entry Manually\" to update this customer's khata.", hi: "आवाज़ से अपना पहला लेन-देन रिकॉर्ड करें या ग्राहक के खाते को अपडेट करने के लिए मैन्युअल रूप से जोड़ें।" },
  "khata.receivedPayment":   { en: "Received payment", hi: "भुगतान मिला" },
  "khata.gaveCredit":        { en: "Gave credit / expense", hi: "उधार दिया / खर्च" },
  "khata.moneyReceived":     { en: "Money Received",   hi: "पैसा मिला" },
  "khata.moneyGiven":        { en: "Money Given",      hi: "पैसा दिया" },
  "khata.completed":         { en: "Completed",        hi: "पूर्ण" },
  "khata.today":             { en: "Today",            hi: "आज" },
  "khata.saveCustomer":      { en: "Save Customer",    hi: "ग्राहक सेव करें" },
  "khata.saveToKhata":       { en: "Save to Khata",    hi: "खाते में सेव करें" },
  "khata.partyType":         { en: "Party Type",       hi: "पार्टी का प्रकार" },
  "khata.customer":          { en: "Customer",         hi: "ग्राहक" },
  "khata.supplier":          { en: "Supplier",         hi: "सप्लायर" },
  "khata.openingBalance":    { en: "Opening Balance (₹)", hi: "शुरुआती शेष (₹)" },
  "khata.phone":             { en: "Phone Number",     hi: "फ़ोन नंबर" },
  "khata.fullName":          { en: "Full Name",        hi: "पूरा नाम" },
  "khata.backToKhata":       { en: "Back to Khata List", hi: "खाता सूची पर वापस जाएं" },
  "khata.noCustomersFound":  { en: "No customers found", hi: "कोई ग्राहक नहीं मिला" },
  "khata.trySearchingAgain": { en: "Try searching with another name or add a new customer.", hi: "किसी अन्य नाम से खोजने का प्रयास करें या नया ग्राहक जोड़ें।" },
  "khata.recordPayment":     { en: "Record Payment (+)", hi: "भुगतान जोड़ें (+)" },
  "khata.whatsappReminder":  { en: "WhatsApp Reminder", hi: "व्हाट्सएप रिमाइंडर" },
  "khata.lastActivity":      { en: "Last activity",    hi: "अंतिम गतिविधि" },
  "khata.addEntryFor":       { en: "के लिए प्रविष्टि जोड़ें", hi: "के लिए प्रविष्टि जोड़ें" },
  "khata.txType":            { en: "Transaction Type", hi: "लेन-देन का प्रकार" },

  // ── Insights & Projection ──
  "insights.title":         { en: "Financial Insights", hi: "वित्तीय अंतर्दृष्टि" },
  "insights.healthScore":   { en: "Financial Health Score", hi: "वित्तीय स्वास्थ्य स्कोर" },
  "insights.excellent":     { en: "Excellent",        hi: "उत्कृष्ट" },
  "insights.onTrack":       { en: "On Track",         hi: "सही राह पर" },
  "insights.needsWork":     { en: "Needs Work",       hi: "सुधार की आवश्यकता" },
  "insights.atRisk":        { en: "At Risk",          hi: "जोखिम में" },
  "projection.title":       { en: "Wealth Projection", hi: "धन विकास अनुमान" },
  "projection.subtitle":    { en: "See how your savings and investments grow over time", hi: "देखें कि समय के साथ आपकी बचत और निवेश कैसे बढ़ते हैं" },
  "projection.year":        { en: "Year",             hi: "वर्ष" },
  "projection.years":       { en: "Years",            hi: "वर्ष" },
  "projection.totalWealth": { en: "Total Projected Wealth", hi: "कुल अनुमानित संपत्ति" },
  "projection.totalInvested":{ en: "Total Invested",  hi: "कुल निवेश" },
  "projection.wealthGain":  { en: "Wealth Gain",      hi: "संपत्ति में वृद्धि" },

  // ── Forms & Dialogs ──
  "form.addTransaction":    { en: "Add Transaction",  hi: "लेन-देन जोड़ें" },
  "form.addAutopay":        { en: "Add Autopay",      hi: "ऑटोपे जोड़ें" },
  "form.newAutopay":        { en: "New Autopay / Recurring", hi: "नया ऑटोपे / आवर्ती" },
  "form.editTransaction":   { en: "Edit Transaction", hi: "लेन-देन संपादित करें" },
  "form.editAutopayRule":   { en: "Edit Autopay Rule", hi: "ऑटोपे नियम संपादित करें" },
  "form.editDetails":       { en: "Update the details below to modify this transaction.", hi: "इस लेन-देन को बदलने के लिए नीचे दिए गए विवरण अपडेट करें।" },
  "form.noActiveBudget":    { en: "No active budget found for", hi: "कोई सक्रिय बजट नहीं मिला:" },
  "form.in":                { en: "in",               hi: "में" },
  "form.deleteTransaction": { en: "Delete Transaction", hi: "लेन-देन हटाएं" },
  "form.deleteAutopayRule": { en: "Delete Autopay Rule", hi: "ऑटोपे नियम हटाएं" },
  "form.deleteAutopay":     { en: "Delete Autopay", hi: "ऑटोपे हटाएं" },
  "form.cannotUndo":        { en: "This action cannot be undone.", hi: "यह कार्रवाई वापस नहीं की जा सकती।" },
  "form.aboutToDelete":     { en: "You are about to permanently delete:", hi: "आप स्थायी रूप से हटाने वाले हैं:" },
  "form.deleting":          { en: "Deleting...",      hi: "हटाया जा रहा है..." },
  "form.adding":            { en: "Adding…",          hi: "जोड़ा जा रहा है..." },
  "form.addNewTx":          { en: "Add New Transaction", hi: "नया लेन-देन जोड़ें" },
  "form.fillDetails":       { en: "Fill in the details or scan a receipt to auto-fill.", hi: "विवरण भरें या ऑटो-फ़िल के लिए रसीद स्कैन करें।" },
  "form.scanSuccess":       { en: "Receipt scanned successfully — please review all fields.", hi: "रसीद सफलतापूर्वक स्कैन हो गई - कृपया सभी फ़ील्ड की जांच करें।" },
  "form.scanLowConf":       { en: "Receipt scanned but some fields may be incorrect — please review carefully.", hi: "रसीद स्कैन हो गई है लेकिन कुछ फ़ील्ड गलत हो सकते हैं - कृपया ध्यान से जांचें।" },
  "form.scanError":         { en: "AI scan unavailable, please fill manually.", hi: "AI स्कैन अनुपलब्ध है, कृपया मैन्युअल रूप से भरें।" },
  "form.txName":            { en: "Transaction Name", hi: "लेन-देन का नाम" },
  "form.txNamePlaceholder": { en: "e.g. Salary Credit", hi: "जैसे: वेतन प्राप्त हुआ" },
  "form.selectCategory":    { en: "Select category",  hi: "श्रेणी चुनें" },
  "form.budgeted":          { en: "Budgeted",         hi: "बजट किया गया" },
  "form.typePlaceholder":   { en: "Debit / Credit",   hi: "नामे / जमा" },
  "form.noBudgetFor":       { en: "No budget for",    hi: "इसके लिए कोई बजट नहीं:" },
  "form.trackSpending":     { en: "Track spending on", hi: "खर्च ट्रैक करें" },
  "form.byCreating":        { en: "by creating a budget below.", hi: "नीचे बजट बनाकर।" },
  "form.alsoCreateBudget":  { en: "Also create a budget for", hi: "इसके लिए बजट भी बनाएं" },
  "form.budgetType":        { en: "Budget type",      hi: "बजट का प्रकार" },
  "form.timeless":          { en: "Timeless",         hi: "सदाबहार (Timeless)" },
  "form.monthly":           { en: "Monthly",          hi: "मासिक (Monthly)" },
  "form.amountLabel":       { en: "Amount (₹)",       hi: "रकम (₹)" },
  "form.amountPlaceholder": { en: "e.g. 5000",        hi: "जैसे: 5000" },
  "form.pickDate":          { en: "Pick a date",      hi: "एक तारीख चुनें" },
  "form.paymentMethod":     { en: "Payment Method",   hi: "भुगतान का तरीका" },
  "form.selectMethod":      { en: "Select method",    hi: "तरीका चुनें" },
  "form.scanReceipt":       { en: "Scan Receipt",     hi: "रसीद स्कैन करें" },
  "form.import":            { en: "Import",           hi: "आयात करें (Import)" },
  "form.saving":            { en: "Saving...",        hi: "सेव किया जा रहा है..." },

  // ── Voice Capture page extras ──
  "voice.pageSubtitle":     { en: "Say what happened in Hindi or English, review details, and save directly to your ledger.", hi: "हिंदी या अंग्रेजी में बोलें, विवरण देखें, और सीधे अपने खाते में सेव करें।" },

  // ── Settings page ──
  "settings.profileDesc":   { en: "Your identity across the platform.", hi: "प्लेटफ़ॉर्म पर आपकी पहचान।" },
  "settings.appearanceDesc":{ en: "Customize how VoiceKhata looks across your workspace.", hi: "VoiceKhata का रूप अपनी workspace में कस्टमाइज़ करें।" },
  "settings.financialDesc": { en: "Keep your financial data accurate for better insights.", hi: "बेहतर अंतर्दृष्टि के लिए अपना वित्तीय डेटा सटीक रखें।" },
  "settings.securityDesc":  { en: "Protect your account with a strong password.", hi: "मज़बूत पासवर्ड से अपना खाता सुरक्षित करें।" },
  "settings.dangerDesc":    { en: "Destructive actions — proceed with extreme caution.", hi: "विनाशकारी क्रियाएं — अत्यंत सावधानी से आगे बढ़ें।" },

  // ── Notifications ──
  "notif.title":            { en: "Notifications",    hi: "सूचनाएं" },
  "notif.markAllRead":      { en: "Mark all read",   hi: "सभी पढ़ा हुआ करें" },
  "notif.clearAll":         { en: "Clear all",        hi: "सभी हटाएं" },
  "notif.all":              { en: "All",              hi: "सभी" },
  "notif.unread":           { en: "Unread",           hi: "अपठित" },
  "notif.budget":           { en: "Budget",           hi: "बजट" },
  "notif.transaction":      { en: "Transaction",      hi: "लेन-देन" },
  "notif.aiInsight":        { en: "AI Insight",       hi: "AI अंतर्दृष्टि" },
  "notif.system":           { en: "System",           hi: "सिस्टम" },
  "notif.goal":             { en: "Goal",             hi: "लक्ष्य" },
  "notif.noNotifications":  { en: "No notifications", hi: "कोई सूचना नहीं" },
  "notif.noMatch":          { en: "No notifications match this filter", hi: "इस फ़िल्टर से कोई सूचना नहीं मिली" },

  // ── Reports ──
  "reports.subtitle":       { en: "Detailed analytics across cash flow, budgets, savings, and investments", hi: "नकदी प्रवाह, बजट, बचत और निवेश का विस्तृत विश्लेषण" },
  "reports.loading":        { en: "Loading reports...", hi: "रिपोर्ट लोड हो रही है..." },
  "reports.totalIncome":    { en: "Total Income",     hi: "कुल आय" },
  "reports.totalExpenses":  { en: "Total Expenses",   hi: "कुल खर्च" },
  "reports.netSavings":     { en: "Net Savings",      hi: "कुल बचत" },
  "reports.savingsRate":    { en: "Savings Rate",     hi: "बचत दर" },
  "reports.expenseRatio":   { en: "Expense Ratio",    hi: "खर्च अनुपात" },
  "reports.avgTx":          { en: "Avg Transaction",  hi: "औसत लेन-देन" },
  "reports.transactions":   { en: "Transactions",     hi: "लेन-देन" },
  "reports.budgetUsed":     { en: "Budget Used",      hi: "प्रयुक्त बजट" },
  "reports.monthlyOverview":{ en: "Monthly Overview", hi: "मासिक अवलोकन" },
  "reports.cashFlowTimeline":{ en: "Cash Flow Timeline", hi: "कैश फ्लो समयरेखा" },
  "reports.financialHealth":{ en: "Financial Health Score", hi: "वित्तीय स्वास्थ्य स्कोर" },
  "reports.noData":         { en: "No data for this period", hi: "इस अवधि के लिए कोई डेटा नहीं" },
  "reports.export":         { en: "Export",           hi: "निर्यात करें" },
  "reports.download":       { en: "Download",         hi: "डाउनलोड करें" },
  "reports.velocity":       { en: "Spending Velocity", hi: "खर्च की गति" },
  "reports.burnRate":       { en: "Burn rate",        hi: "दैनिक खर्च दर" },
  "reports.projectedEnd":   { en: "Projected month-end", hi: "महीने के अंत का अनुमान" },
  "reports.daysWithSpend":  { en: "Days with spend",  hi: "खर्च वाले दिन" },
  "reports.spendFreeDays":  { en: "Spend-free days",  hi: "बिना खर्च वाले दिन" },
  "reports.largestSingleDay":{ en: "Largest single day", hi: "सबसे बड़ा खर्च दिन" },
  "reports.medianTransaction":{ en: "Median transaction", hi: "मध्यम लेन-देन" },
  "reports.incomeQuality":  { en: "Income Quality",   hi: "आय की गुणवत्ता" },
  "reports.uniqueSources":  { en: "Unique sources",   hi: "विशिष्ट स्रोत" },
  "reports.largestCredit":  { en: "Largest credit",   hi: "सबसे बड़ी जमा राशि" },
  "reports.stability":      { en: "Stability (6mo)",  hi: "स्थिरता (6 माह)" },
  "reports.netRetained":    { en: "Net retained",     hi: "शुद्ध बची आय" },
  "reports.monthlySip":     { en: "Monthly SIP",      hi: "मासिक एसआईपी" },
  "reports.categoryBreakdown":{ en: "Category Breakdown", hi: "श्रेणीवार विवरण" },
  "reports.budgetUtilisation":{ en: "Budget Utilisation", hi: "बजट उपयोग" },
  "reports.savingsProjection":{ en: "Savings Projection", hi: "बचत का अनुमान" },
  "reports.savingsGoals":   { en: "Savings Goals",    hi: "बचत लक्ष्य" },
  "reports.sipInvestments": { en: "SIP & Investments", hi: "एसआईपी और निवेश" },
  "reports.recurringPanel": { en: "Recurring Panel",  hi: "आवर्ती पैनल" },
  "reports.merchantIntelligence":{ en: "Merchant Intelligence", hi: "व्यापारी विश्लेषण" },
  "reports.anomalyFlags":   { en: "Anomaly Flags",    hi: "असामान्य लेन-देन" },
  "reports.ytdSummary":     { en: "Year-to-Date Summary", hi: "वार्षिक सारांश" },
  "reports.ytdIncome":      { en: "YTD Income",       hi: "वार्षिक कुल आय" },
  "reports.ytdExpense":     { en: "YTD Expense",      hi: "वार्षिक कुल खर्च" },
  "reports.ytdSavings":     { en: "YTD Savings",      hi: "वार्षिक कुल बचत" },
  "reports.ytdRate":        { en: "YTD Rate",         hi: "वार्षिक बचत दर" },
  "reports.annualGoal":     { en: "Annual Goal",      hi: "वार्षिक लक्ष्य" },
  "reports.bestMonth":      { en: "Best month",       hi: "सर्वोत्तम महीना" },
  "reports.worstMonth":     { en: "Worst month",      hi: "सबसे खराब महीना" },
  "reports.goalTrack":      { en: "Goal track",       hi: "लक्ष्य स्थिति" },
  "reports.onTrack":        { en: "✓ On track",       hi: "✓ सही गति पर" },
  "reports.behindPace":     { en: "⚠ Behind pace",    hi: "⚠ लक्ष्य से पीछे" },
  "reports.noGoalSet":      { en: "No goal set",      hi: "कोई लक्ष्य नहीं" },
  "reports.noTransactions": { en: "No transactions this month", hi: "इस महीने कोई लेन-देन नहीं" },
  "reports.noExpenseData":  { en: "No expense data for this month", hi: "इस महीने कोई खर्च डेटा नहीं" },
  "reports.noBudgets":      { en: "No active budgets for this month.", hi: "इस महीने के लिए कोई सक्रिय बजट नहीं है।" },
  "reports.noGoals":        { en: "No savings goals found.", hi: "कोई बचत लक्ष्य नहीं मिला।" },
  "reports.noInvestments":  { en: "No investments tracked.", hi: "कोई निवेश ट्रैक नहीं किया गया।" },
  "reports.noRecurring":    { en: "No recurring transactions.", hi: "कोई आवर्ती लेन-देन नहीं।" },
  "reports.noAnomalies":    { en: "No anomalies detected for this month", hi: "इस महीने कोई असामान्य लेन-देन नहीं मिला" },
  "reports.allocated":      { en: "Allocated",        hi: "आवंटित" },
  "reports.spent":          { en: "Spent",            hi: "खर्च हुआ" },
  "reports.remaining":      { en: "Remaining",        hi: "शेष" },
  "reports.unrealisedPnl":  { en: "Unrealised P/L",   hi: "अप्राप्त लाभ/हानि" },
  "reports.monthlyCommitted":{ en: "Monthly committed", hi: "मासिक प्रतिबद्ध" },
  "reports.renewalsIn7Days":{ en: "Renewals in 7 days", hi: "7 दिनों में नवीनीकरण" },
  "reports.current":        { en: "Current",          hi: "वर्तमान" },
  "reports.previous":       { en: "Previous",         hi: "पिछला" },
  "reports.category":       { en: "Category",         hi: "श्रेणी" },
  "reports.mom":            { en: "MoM",              hi: "मासिक बदलाव" },
  "reports.holding":        { en: "Holding",          hi: "होल्डिंग" },
  "reports.invested":       { en: "Invested",         hi: "निवेश किया" },
  "reports.pnl":            { en: "P/L",              hi: "लाभ/हानि" },
  "reports.name":           { en: "Name",             hi: "नाम" },
  "reports.amount":         { en: "Amount",           hi: "राशि" },
  "reports.nextRun":        { en: "Next run",         hi: "अगला चक्र" },
  "reports.date":           { en: "Date",             hi: "तारीख" },
  "reports.threshold":      { en: "Threshold",        hi: "सीमा" },

  // ── Reports: Segment-aware keys ──
  "reports.title":          { en: "Reports",           hi: "रिपोर्ट" },
  "reports.personalTitle":  { en: "Money Health",      hi: "धन स्वास्थ्य" },
  "reports.businessTitle":  { en: "Business Pulse",    hi: "बिज़नेस पल्स" },
  "reports.personalSubtitle":{ en: "Your savings, spending, and goals at a glance", hi: "बचत, खर्च और लक्ष्य — एक नज़र में" },
  "reports.businessSubtitle":{ en: "Revenue, cash flow, and outstanding dues", hi: "राजस्व, नकदी प्रवाह और बकाया" },
  "reports.revenue":        { en: "Revenue",           hi: "राजस्व" },
  "reports.operatingCosts": { en: "Operating Costs",   hi: "परिचालन लागत" },
  "reports.netCashFlow":    { en: "Net Cash Flow",     hi: "शुद्ध नकदी प्रवाह" },
  "reports.outstandingReceivables":{ en: "Receivables", hi: "बकाया (लेना)" },
  "reports.outstandingPayables":{ en: "Payables",      hi: "बकाया (देना)" },
  "reports.earningsVsSpending":{ en: "Earnings vs Spending", hi: "आय बनाम खर्च" },
  "reports.revenueVsCosts": { en: "Revenue vs Costs",  hi: "राजस्व बनाम लागत" },
  "reports.savingsAndGoals":{ en: "Savings & Goals",   hi: "बचत और लक्ष्य" },
  "reports.budgetAndBurn":  { en: "Budget & Burn Rate", hi: "बजट और दैनिक खर्च दर" },
  "reports.receivablesPayables":{ en: "Receivables & Payables", hi: "लेना और देना" },
  "reports.showMore":       { en: "Show detailed analytics", hi: "विस्तृत विश्लेषण दिखाएं" },
  "reports.showLess":       { en: "Show less",         hi: "कम दिखाएं" },
  "reports.netProfit":      { en: "Net Profit",        hi: "शुद्ध लाभ" },
  "reports.income":         { en: "Income",            hi: "आय" },
  "reports.expense":        { en: "Expense",           hi: "खर्च" },
  "reports.balance":        { en: "Balance",           hi: "शेष" },
  "reports.personalSection":{ en: "Personal",          hi: "व्यक्तिगत" },
  "reports.businessSection":{ en: "Business",          hi: "व्यवसाय" },
  "reports.budgetHealth":   { en: "Budget Health",     hi: "बजट स्वास्थ्य" },
  "reports.topCategories":  { en: "Top Categories",    hi: "शीर्ष श्रेणियाँ" },
  "reports.noReceivables":  { en: "No outstanding receivables", hi: "कोई बकाया नहीं" },
  "reports.noPayables":     { en: "No outstanding payables", hi: "कोई देय बकाया नहीं" },
  "reports.overdue":        { en: "Overdue",           hi: "अतिदेय" },
  "reports.dueSoon":        { en: "Due soon",          hi: "जल्द देय" },
  "reports.collected":      { en: "Collected",         hi: "वसूल किया" },

  // ── Money Growth / Business Growth ──
  "growth.title":           { en: "Money Growth",     hi: "पैसे की बढ़त" },
  "growth.revenue":         { en: "Revenue",          hi: "राजस्व" },
  "growth.profit":          { en: "Profit",           hi: "लाभ" },
  "growth.growth":          { en: "Growth",           hi: "बढ़त" },
  "growth.thisMonth":       { en: "This Month",       hi: "इस महीने" },
  "growth.twinTitle":       { en: "Building Your Financial Digital Twin...", hi: "आपका वित्तीय डिजिटल ट्विन तैयार हो रहा है..." },
  "growth.twinDesc":        { en: "Analyzing your transactions and generating intelligence", hi: "आपके लेन-देन का विश्लेषण और वित्तीय अंतर्दृष्टि तैयार की जा रही है" },
  "growth.hubTitle":        { en: "AI Money Growth Center", hi: "एआई मनी ग्रोथ सेंटर" },
  "growth.hubDesc":         { en: "Your Financial Digital Twin — real-time intelligence on health, growth, and next best moves.", hi: "आपका वित्तीय डिजिटल ट्विन — स्वास्थ्य, विकास और सर्वोत्तम कदमों पर रीयल-टाइम अंतर्दृष्टि।" },
  "growth.refresh":         { en: "Refresh Intelligence", hi: "अंतर्दृष्टि ताज़ा करें" },
  "growth.runBusiness":     { en: "Run a business?",  hi: "क्या आपका कोई व्यवसाय है?" },
  "growth.runBusinessDesc": { en: "Set up your Business Growth Hub to unlock shopkeeper intelligence, supplier tracking, and business-specific insights.", hi: "दुकानदार विश्लेषण, सप्लायर ट्रैकिंग और व्यावसायिक अंतर्दृष्टि अनलॉक करने के लिए बिज़नेस ग्रोथ हब सेट करें।" },
  "growth.setupBusiness":   { en: "Set Up Business",  hi: "बिज़नेस सेट अप करें" },
  "growth.businessGrowthHub":{ en: "Business Growth Hub", hi: "बिज़नेस ग्रोथ हब" },
  "growth.readiness":       { en: "Readiness",        hi: "तैयारी स्तर" },
  "growth.howMoneyUsed":    { en: "How is your money being used?", hi: "आपका पैसा कैसे इस्तेमाल हो रहा है?" },
  "growth.howMoneyUsedDesc":{ en: "Categorize your transactions to separate Business expenses from Personal and Owner Withdrawals.", hi: "व्यावसायिक खर्चों को व्यक्तिगत और मालिक की निकासी से अलग करने के लिए अपने लेन-देन वर्गीकृत करें।" },
  "growth.howMoneyMoves":   { en: "How your money moves", hi: "पैसा कैसे घूमता है" },
  "growth.customers":       { en: "Customers",        hi: "ग्राहक" },
  "growth.suppliers":       { en: "Suppliers",        hi: "सप्लायर्स" },
  "growth.products":        { en: "Products",         hi: "उत्पाद" },
  "growth.connectedAccounts":{ en: "Connected Accounts", hi: "जुड़े हुए खाते" },
  "growth.noData":          { en: "No financial data available yet. Start adding transactions to power your growth engine.", hi: "अभी कोई वित्तीय डेटा उपलब्ध नहीं है। अपने विकास इंजन को सक्रिय करने के लिए लेन-देन जोड़ना शुरू करें।" },

  // ── AI Assistant ──
  "ai.clearChat":           { en: "Clear chat",       hi: "चैट साफ़ करें" },
  "ai.howCanIHelp":         { en: "How can I help you today?", hi: "आज मैं आपकी क्या सहायता कर सकता हूँ?" },
  "ai.howCanIHelpBusiness": { en: "How can I help with your business today?", hi: "आज मैं आपके व्यापार में क्या सहायता कर सकता हूँ?" },
  "ai.askPrompt":           { en: "Ask about your finances or say", hi: "अपने वित्त के बारे में पूछें या कहें" },
  "ai.askPromptBusiness":   { en: "Ask about customers, transactions, sales or payments, or say", hi: "ग्राहकों, लेन-देन, बिक्री या भुगतान के बारे में पूछें या कहें" },
  "ai.titleBusiness":       { en: "AI Assistant",    hi: "एआई सहायक" },
  "ai.replyingTo":          { en: "Replying to",      hi: "जवाब दे रहे हैं" },
  "ai.you":                 { en: "You",              hi: "आप" },
  "ai.enterToSend":         { en: "Enter to send",    hi: "भेजने के लिए Enter दबाएं" },
  "ai.shiftEnter":          { en: "Shift+Enter for new line", hi: "नई पंक्ति के लिए Shift+Enter" },
  "ai.logTransaction":      { en: "Log transaction",  hi: "लेन-देन जोड़ें" },
  "ai.scanReceipt":         { en: "Scan receipt",     hi: "रसीद स्कैन करें" },
  "ai.importScreenshots":   { en: "Import screenshots", hi: "स्क्रीनशॉट आयात करें" },
  "ai.setBudget":           { en: "Set a budget",     hi: "बजट सेट करें" },
  "ai.comingSoon":          { en: "Coming soon",      hi: "जल्द आ रहा है" },
  "ai.listening":           { en: "Listening... Speak naturally in Hindi or English", hi: "सुन रहा हूँ... हिंदी या अंग्रेजी में स्वाभाविक रूप से बोलें" },

  // ── Settings ──
  "settings.account":       { en: "Account",          hi: "खाता" },
  "settings.profile":       { en: "Profile",          hi: "प्रोफ़ाइल" },
  "settings.appearance":    { en: "Appearance",       hi: "दिखावट" },
  "settings.financial":     { en: "Financial",        hi: "वित्तीय" },
  "settings.security":      { en: "Security",         hi: "सुरक्षा" },
  "settings.danger":        { en: "Danger Zone",      hi: "खतरा क्षेत्र" },
  "settings.theme":         { en: "Theme",            hi: "थीम" },
  "settings.themeTitle":    { en: "Customize how VoiceKhata looks", hi: "चुनें कि वॉइसखाता कैसा दिखे" },
  "settings.themeSubtitle": { en: "Choose your preferred appearance for the entire workspace.", hi: "पूरे कार्यक्षेत्र के लिए अपना पसंदीदा स्वरूप चुनें।" },
  "settings.dark":          { en: "Dark",             hi: "डार्क" },
  "settings.light":         { en: "Light",            hi: "लाइट" },
  "settings.selected":      { en: "Selected",         hi: "चयनित" },
  "settings.deleteAccount": { en: "Delete Account",   hi: "खाता हटाएं" },
  "settings.irreversible":  { en: "Irreversible Actions", hi: "अपरिवर्तनीय क्रियाएं" },
  "settings.irreversibleDesc":{ en: "Actions on this page cannot be undone. Your data will be permanently lost.", hi: "इस पृष्ठ पर की गई कार्रवाइयों को पूर्ववत नहीं किया जा सकता। आपका डेटा स्थायी रूप से नष्ट हो जाएगा।" },
  "settings.deleteConfirmTitle":{ en: "Delete your account?", hi: "क्या आप वाकई अपना खाता हटाना चाहते हैं?" },
  "settings.deleteConfirmDesc":{ en: "This permanently removes your account and all data — transactions, budgets, goals, everything. This action cannot be undone.", hi: "यह आपके खाते और सभी डेटा — लेन-देन, बजट, लक्ष्य, सब कुछ स्थायी रूप से हटा देता है। इसे पूर्ववत नहीं किया जा सकता।" },
  "settings.fullName":      { en: "Full Name",        hi: "पूरा नाम" },
  "settings.country":       { en: "Country",          hi: "देश" },
  "settings.gmailImport":   { en: "Gmail Auto-Import", hi: "जीमेल ऑटो-इंपोर्ट" },
  "settings.gmailImportDesc":{ en: "Automatically import UPI & bank transactions from your Gmail inbox.", hi: "अपने जीमेल इनबॉक्स से यूपीआई और बैंक लेन-देन स्वतः आयात करें।" },
  "settings.connected":     { en: "Connected",        hi: "जुड़ा हुआ" },
  "settings.disconnect":    { en: "Disconnect",       hi: "डिस्कनेक्ट करें" },
  "settings.connectGmail":  { en: "Connect Gmail",    hi: "जीमेल कनेक्ट करें" },
  "settings.changePassword":{ en: "Change Password",  hi: "पासवर्ड बदलें" },
  "settings.passwordHelp":  { en: "Use a strong, unique password. Minimum 6 characters.", hi: "एक मजबूत और अद्वितीय पासवर्ड का उपयोग करें। न्यूनतम 6 वर्ण।" },
  "settings.currentPassword":{ en: "Current Password", hi: "वर्तमान पासवर्ड" },
  "settings.newPassword":   { en: "New Password",     hi: "नया पासवर्ड" },
  "settings.confirmPassword":{ en: "Confirm New Password", hi: "नए पासवर्ड की पुष्टि करें" },
  "settings.updatePassword":{ en: "Update Password",  hi: "पासवर्ड अपडेट करें" },
  "settings.enterCurrentPassword": { en: "Enter current password", hi: "वर्तमान पासवर्ड दर्ज करें" },
  "settings.enterNewPassword": { en: "Enter new password", hi: "नया पासवर्ड दर्ज करें" },
  "settings.repeatNewPassword": { en: "Repeat new password", hi: "नया पासवर्ड दोहराएं" },
  "settings.passwordsDoNotMatch": { en: "Passwords don't match", hi: "पासवर्ड मेल नहीं खाते" },
  "settings.passwordsMatch": { en: "Passwords match", hi: "पासवर्ड मेल खाते हैं" },
  "settings.updating":      { en: "Updating…",        hi: "अपडेट हो रहा है…" },
  "settings.installApp":    { en: "Install App",      hi: "ऐप इंस्टॉल करें" },
  "settings.installVoiceKhata": { en: "Install VoiceKhata", hi: "VoiceKhata इंस्टॉल करें" },
  "settings.installDesc":   { en: "Add to home screen for quick access", hi: "त्वरित पहुंच के लिए होम स्क्रीन पर जोड़ें" },
  "settings.installed":     { en: "App Installed",    hi: "ऐप इंस्टॉल किया गया" },
  "settings.appInstalledDesc": { en: "VoiceKhata is on your home screen", hi: "VoiceKhata आपकी होम स्क्रीन पर है" },
  "settings.signOut":       { en: "Sign Out",         hi: "साइन आउट" },
  "settings.signOutDesc":   { en: "End your current session on this device.", hi: "इस डिवाइस पर अपना वर्तमान सत्र समाप्त करें।" },
  "settings.verified":      { en: "Verified",         hi: "सत्यापित" },
  "settings.changePhoto":   { en: "Change photo",     hi: "फ़ोटो बदलें" },
  "settings.removePhoto":   { en: "Remove",           hi: "हटाएं" },
  "settings.savePhoto":     { en: "Save photo",       hi: "फ़ोटो सेव करें" },
  "settings.displayName":   { en: "Display Name",     hi: "प्रदर्शित नाम" },
  "settings.displayNameDesc": { en: "Shown across the entire app. 32 characters max.", hi: "पूरे ऐप में दिखाया जाता है। अधिकतम 32 वर्ण।" },
  "settings.emailAddress":  { en: "Email Address",    hi: "ईमेल पता" },
  "settings.loginEmailDesc":{ en: "Your login email.", hi: "आपका लॉगिन ईमेल।" },
  "settings.dob":           { en: "Date of Birth",    hi: "जन्म तिथि" },
  "settings.dobDesc":       { en: "Private — used for age-based insights only.", hi: "निजी — केवल उम्र-आधारित वित्तीय अंतर्दृष्टि के लिए उपयोग किया जाता है।" },
  "settings.saveProfile":   { en: "Save Profile",     hi: "प्रोफ़ाइल सेव करें" },
  "settings.saving":        { en: "Saving…",          hi: "सेव हो रहा है…" },
  "settings.pickDate":      { en: "Pick a date",      hi: "तारीख चुनें" },
  "settings.weak":          { en: "Weak",             hi: "कमज़ोर" },
  "settings.fair":          { en: "Fair",             hi: "सामान्य" },
  "settings.good":          { en: "Good",             hi: "अच्छा" },
  "settings.strong":        { en: "Strong",           hi: "मज़बूत" },
  "settings.strength":      { en: "Strength:",        hi: "मजबूती:" },

  // ── Days of week ──
  "common.sunday":          { en: "Sunday",           hi: "रविवार" },
  "common.monday":          { en: "Monday",           hi: "सोमवार" },
  "common.tuesday":         { en: "Tuesday",          hi: "मंगलवार" },
  "common.wednesday":       { en: "Wednesday",        hi: "बुधवार" },
  "common.thursday":        { en: "Thursday",         hi: "गुरुवार" },
  "common.friday":          { en: "Friday",           hi: "शुक्रवार" },
  "common.saturday":        { en: "Saturday",         hi: "शनिवार" },
};

// ─── Provider ─────────────────────────────────────────────────────────────────
export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      const stored = window.localStorage.getItem("voicekhata:language");
      if (stored === "en" || stored === "hi") return stored as Language;
    }
    return "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== "undefined") {
      window.localStorage.setItem("voicekhata:language", lang);
    }
  };

  const t = (key: string): string => {
    const entry = translations[key];
    if (!entry) return key;
    return entry[language] ?? entry["en"] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

// ─── Hook ─────────────────────────────────────────────────────────────────────
export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within a LanguageProvider");
  return context;
}
