-- ==============================================================================
-- FinEase Supabase Database Migration: 01_initial_schema
-- Description: Core schema matching live production database
-- ==============================================================================

-- 1. Enable Required Extensions
create extension if not exists "uuid-ossp";
create extension if not exists "pgcrypto";

-- 2. User Profiles Table
create table if not exists public.user_profiles (
  id                   uuid not null default gen_random_uuid(),
  firebase_uid         text not null unique,
  full_name            text,
  country              text,
  currency             text default 'USD',
  monthly_income       numeric,
  income_source        text,
  savings_goal         numeric,
  financial_experience text,
  dob                  date,
  profile_pic          text,
  gmail_connected      boolean default false,
  created_at           timestamptz default now(),
  constraint user_profiles_pkey primary key (id)
);

-- 3. Transactions Table
create table if not exists public.transactions (
  id           bigint generated by default as identity primary key,
  firebase_uid text not null references public.user_profiles(firebase_uid) on delete cascade,
  transaction  text,
  category     text,
  amount       numeric not null,
  date         date not null default current_date,
  type         text not null check (type in ('Credit', 'Debit')),
  method       text,
  status       text default 'Completed',
  created_at   timestamptz default now()
);

-- 4. Budgets Table
create table if not exists public.budgets (
  id           uuid not null default gen_random_uuid() primary key,
  firebase_uid text not null references public.user_profiles(firebase_uid) on delete cascade,
  category     text not null,
  amount       numeric not null,
  month        text not null,
  duration     text not null default 'monthly',
  created_at   timestamptz default now()
);

-- 5. User Budget Caps Table
create table if not exists public.user_budget_caps (
  id           uuid not null default gen_random_uuid() primary key,
  firebase_uid text not null references public.user_profiles(firebase_uid) on delete cascade,
  month        text not null,
  total_cap    numeric not null,
  created_at   timestamptz not null default now()
);

-- 6. Savings Goals Table
create table if not exists public.savings_goals (
  id            uuid not null default gen_random_uuid() primary key,
  firebase_uid  text not null references public.user_profiles(firebase_uid) on delete cascade,
  name          text not null,
  target_amount numeric not null,
  saved_amount  numeric default 0,
  deadline      date,
  color         text default '#4ade80',
  created_at    timestamptz default now()
);

-- 7. SIP Plans Table
create table if not exists public.sip_plans (
  id              uuid not null default gen_random_uuid() primary key,
  firebase_uid    text not null references public.user_profiles(firebase_uid) on delete cascade,
  monthly_amount  numeric not null,
  duration_years  integer not null,
  expected_return numeric default 12,
  start_date      date default current_date,
  active          boolean default true,
  created_at      timestamptz default now()
);

-- 8. Manual Investments Table
create table if not exists public.manual_investments (
  id              uuid not null default gen_random_uuid() primary key,
  firebase_uid    text not null references public.user_profiles(firebase_uid) on delete cascade,
  name            text not null,
  type            text not null,
  amount_invested numeric not null,
  expected_return numeric default 10,
  added_at        timestamptz default now(),
  ticker          text,
  quantity        numeric,
  bought_price    numeric,
  current_price   numeric,
  bought_date     date
);

-- 9. Recurring Transactions Table
create table if not exists public.recurring_transactions (
  id           uuid not null default gen_random_uuid() primary key,
  firebase_uid text not null references public.user_profiles(firebase_uid) on delete cascade,
  transaction  text not null,
  category     text not null,
  amount       numeric not null,
  type         text not null,
  method       text not null,
  frequency    text not null,
  start_date   date not null,
  next_run     date not null,
  end_date     date,
  active       boolean default true,
  created_at   timestamptz default now()
);

-- 10. Recurring Savings Table
create table if not exists public.recurring_savings (
  id           uuid not null default gen_random_uuid() primary key,
  firebase_uid text not null references public.user_profiles(firebase_uid) on delete cascade,
  label        text not null,
  amount       numeric not null,
  frequency    text not null,
  active       boolean default true,
  created_at   timestamptz default now()
);

-- 11. Notifications Table
create table if not exists public.notifications (
  id           uuid not null default gen_random_uuid() primary key,
  firebase_uid text not null references public.user_profiles(firebase_uid) on delete cascade,
  type         text not null check (type in ('budget_alert', 'transaction', 'ai_insight', 'system', 'goal')),
  title        text not null,
  message      text not null,
  metadata     jsonb default '{}'::jsonb,
  read         boolean default false,
  created_at   timestamptz default now()
);

-- 12. Alert Rules Table
create table if not exists public.alert_rules (
  id           uuid not null default gen_random_uuid() primary key,
  firebase_uid text not null references public.user_profiles(firebase_uid) on delete cascade,
  name         text not null,
  condition    text not null check (condition in ('budget_exceed', 'large_transaction', 'monthly_summary', 'low_balance', 'goal_progress')),
  threshold    numeric,
  category     text,
  channel      text[] default array['in_app']::text[],
  enabled      boolean default true,
  created_at   timestamptz default now()
);

-- 13. Notification Preferences Table
create table if not exists public.notification_prefs (
  firebase_uid        text not null primary key references public.user_profiles(firebase_uid) on delete cascade,
  quiet_hours_start   integer,
  quiet_hours_end     integer,
  in_app              boolean default true,
  email               boolean default false,
  budget_alerts       boolean default true,
  transaction_alerts  boolean default true,
  ai_insights         boolean default true,
  system_alerts       boolean default true,
  updated_at          timestamptz default now()
);

-- 14. Merchant Memory Table
create table if not exists public.merchant_memory (
  id              uuid not null default gen_random_uuid() primary key,
  firebase_uid    text,
  raw_input       text not null,
  normalized_name text not null,
  merchant_type   text,
  category        text check (category in ('Food', 'Shopping', 'Transport', 'Utilities', 'Health', 'Entertainment', 'Subscription', 'Income', 'Other')),
  tags            text[] default '{}'::text[],
  confidence      numeric default 0.5 check (confidence >= 0 and confidence <= 1),
  hit_count       integer not null default 1,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- 15. Yearly Budget Summary Table
create table if not exists public.yearly_budget_summary (
  id           uuid not null default gen_random_uuid() primary key,
  firebase_uid text not null references public.user_profiles(firebase_uid) on delete cascade,
  year         integer not null,
  category     text not null,
  total_budget numeric not null default 0,
  total_spent  numeric not null default 0,
  total_saved  numeric default 0,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- 16. Gmail Sync & Backend Tables
create table if not exists public.gmail_tokens (
  id                uuid not null default gen_random_uuid() primary key,
  firebase_uid      text not null unique references public.user_profiles(firebase_uid) on delete cascade,
  access_token      text,
  refresh_token     text,
  access_token_enc  bytea,
  refresh_token_enc bytea,
  expiry_date       bigint,
  created_at        timestamptz default now()
);

create table if not exists public.processed_emails (
  id           uuid not null default gen_random_uuid() primary key,
  firebase_uid text not null references public.user_profiles(firebase_uid) on delete cascade,
  gmail_id     text not null,
  processed_at timestamptz default now()
);

-- 17. Avatars Storage Bucket Setup
insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do update set public = true;
